### ISSUE TITLE
Due to an update at discord, the theme no longer works completely.

### ISSUE THREAD

**Issue by rowBeeX** [SquirrelKiev/NewcordRevived#1]
According to [[Announcement] Themes/Plugins/Custom CSS for BetterDiscord are broken](https://www.reddit.com/r/BetterDiscord/comments/s0zxwy/announcement_themespluginscustom_css_for/) many discord themes are no longer fully functional.

Is the theme also maintained here in this fork / repository, or is it just hosted here?

**Comment by SquirrelKiev** [comment]
Thanks for bringing this to my attention, didn't know about that. Also, plan is for this fork to be a maintained version of Newcord. Will push a fix soon 👍

**Comment by SquirrelKiev** [comment]
Fixed, should just need to refresh your discord cache and you'll be good.

**Comment by rowBeeX** [comment]
Yes, everything works as it did before (as far as I can tell)
