### ISSUE TITLE
[question] Window border

### ISSUE THREAD

**Issue by shi-gg** [SquirrelKiev/NewcordRevived#3]
Hey,
could you please tell me where you set the window border in the css because I want to make it thiner/remove it!

Thanks
~ Luna

**Comment by SquirrelKiev** [comment]
For removing the border, you'd want to add `/*` to the beginning of line 24 (the line that says `@import url(https://squirrelkiev.github.io/NewcordRevived/src/stuff/paddingWindow.css);`) in newcord.theme.css and add `*/` at the end. 
Line would then be `/*@import url(https://squirrelkiev.github.io/NewcordRevived/src/stuff/paddingWindow.css);*/`
For customising the border, I definitely need to work on making Newcord a little more customisable.
