### ISSUE TITLE
Unpainted elements

### ISSUE THREAD

**Issue by Cyril-R0** [SquirrelKiev/NewcordRevived#5]
Hello, can you fix the background fill in the channels -Home and Browse channel?

![shot1](https://user-images.githubusercontent.com/20502253/221437542-16c3552a-7412-4c88-9b9a-b963695863c3.png)
![shot2](https://user-images.githubusercontent.com/20502253/221437546-6428ef25-cd49-4d74-b8d6-e2d44de85f30.png)

**Comment by SquirrelKiev** [comment]
Just noticed this was here, on it.
